apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydocker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mydocker
  template:
    metadata:
      labels:
        app: mydocker
    spec:
      containers:
        - name: mydocker
          image: prakshigupta14/mydocker:latest
          ports:
            - containerPort: 80
